// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Owner struct {
	ID           string  `json:"id"`
	Reputation   *int    `json:"reputation"`
	ProfileImage *string `json:"profileImage"`
	DisplayName  *string `json:"displayName"`
	Link         *string `json:"link"`
}

type Post struct {
	ID               string  `json:"id"`
	Owner            *Owner  `json:"owner"`
	Score            *int    `json:"score"`
	Type             *string `json:"type"`
	Link             *string `json:"link"`
	LastEditDate     *int    `json:"lastEditDate"`
	LastActivityDate *int    `json:"lastActivityDate"`
	CreationDate     *int    `json:"creationDate"`
}

type Question struct {
	ID               string    `json:"id"`
	Type             *string   `json:"type"`
	Owner            *Owner    `json:"owner"`
	Score            *int      `json:"score"`
	Tags             []*string `json:"tags"`
	Link             *string   `json:"link"`
	Title            *string   `json:"title"`
	LastActivityDate *int      `json:"lastActivityDate"`
	CreationDate     *int      `json:"creationDate"`
}
